 server:
   port: 8082

 spring:
   datasource:
     url: jdbc:mysql://localhost:3306/hotelDb
     username: root
     password: test
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
   application:
     name: Hotel-Service

 eureka:
   instance:
     prefer-ip-address: true
   client:
     fetch-registry: true
     register-with-eureka: true
     serviceUrl:
       defaultZone: http://localhost:8761/eureka
